import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
import { registerSW } from 'virtual:pwa-register'
import App from './App.vue'
import Home from './pages/Home.vue'
import Chat from './pages/Chat.vue'
import './styles/main.css'
import { initTheme } from './composables/useTheme'

initTheme()

const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/', component: Home },
    { path: '/chat', component: Chat },
  ],
})

// Register the service worker generated by vite-plugin-pwa.
// autoUpdate: silently checks for updates and activates new SW when available.
const updateSW = registerSW({
  onNeedRefresh() {
    // New content is available; user can reload to get the latest version
    console.log('New content available. Reload to update.')
  },
  onOfflineReady() {
    // App shell is cached and ready to work offline
    console.log('App ready to work offline.')
  },
})

createApp(App).use(router).mount('#app')

// Expose update function globally if needed for manual refresh prompts
window.__pwaUpdateSW = updateSW
