import { createApp } from "vue";
import { createRouter, createWebHistory } from "vue-router";
import { registerSW } from "virtual:pwa-register";
import App from "./App.vue";
import DashboardPage from "./pages/dashboard/DashboardPage.vue";
import MonitoringPage from "./pages/tracker/MonitoringPage.vue";
import ReportsPage from "./pages/reports/ReportsPage.vue";
import MePage from "./pages/me/MePage.vue";
import AccountPage from "./pages/me/AccountPage.vue";
import ItemsPage from "./pages/me/ItemsPage.vue";
import SavingsPage from "./pages/me/SavingsPage.vue";
import AnalyticsPage from "./pages/me/AnalyticsPage.vue";
import DebtNotePage from "./pages/me/DebtNotePage.vue";
import DebtNoteDetailPage from "./pages/me/DebtNoteDetailPage.vue";
import DebtNoteJoinPage from "./pages/me/DebtNoteJoinPage.vue";
import NotificationsPage from "./pages/me/NotificationsPage.vue";
import ChatPage from "./pages/chat/ChatPage.vue";
import OnboardingPage from "./pages/auth/OnboardingPage.vue";
import LockScreen from "./pages/auth/LockScreen.vue";
import "./styles/main.css";
import { initTheme } from "./composables/useTheme";
import {
	addAppNotification,
	db,
	sessionUnlocked,
	restoreSessionUnlocked,
} from "./db/budgetDb";
import {
	applyDebtPushData,
	listenForegroundMessages,
	refreshGlobalDebtSync,
	registerFcmToken,
	setDebtSyncNotifier,
	syncFirebaseUserProfile,
} from "./firebase";

initTheme();

const router = createRouter({
	history: createWebHistory(),
	routes: [
		{ path: "/", redirect: "/dashboard" },
		{ path: "/dashboard", component: DashboardPage },
		{ path: "/tracker", component: MonitoringPage },
		{ path: "/reports", component: ReportsPage },
		{ path: "/me", component: MePage },
		{ path: "/me/account", component: AccountPage },
		{ path: "/me/items", component: ItemsPage },
		{ path: "/me/savings", component: SavingsPage },
		{ path: "/me/analytics", component: AnalyticsPage },
		{ path: "/me/debt-note", component: DebtNotePage },
		{ path: "/me/debt-note/join", component: DebtNoteJoinPage },
		{ path: "/me/debt-note/:id", component: DebtNoteDetailPage },
		{ path: "/notifications", component: NotificationsPage },
		{ path: "/chat", component: ChatPage },
		{ path: "/onboarding", component: OnboardingPage },
		{ path: "/lock", component: LockScreen },
	],
});

router.beforeEach(async (to) => {
	const profile = await db.userProfiles.get(1);

	if (!profile?.onboardingCompleted) {
		if (to.path !== "/onboarding") return "/onboarding";
		return true;
	}

	if (profile.lockEnabled && !sessionUnlocked) {
		restoreSessionUnlocked();
	}

	if (profile.lockEnabled && !sessionUnlocked) {
		if (to.path !== "/lock") return "/lock";
		return true;
	}

	if (to.path === "/onboarding" || to.path === "/lock") return "/dashboard";

	return true;
});

// Register the service worker generated by vite-plugin-pwa.
// autoUpdate: silently checks for updates and activates new SW when available.
const updateSW = registerSW({
	immediate: true,
	onRegisteredSW(_swUrl, registration) {
		// Avoid reload storms: only check for updates periodically, don't force reload here.
		if (!registration) return;
		setInterval(() => {
			void registration.update();
		}, 60 * 60 * 1000);
	},
	onNeedRefresh() {
		console.log("New content available. Reload to update.");
	},
	onOfflineReady() {
		console.log("App ready to work offline.");
	},
});

createApp(App).use(router).mount("#app");

// Expose update function globally if needed for manual refresh prompts
window.__pwaUpdateSW = updateSW;

function showDebtNotification(title: string, body: string) {
	if ("Notification" in window && Notification.permission === "granted") {
		new Notification(title, { body, icon: "/pwa-192x192.png" });
	}
}

async function initFirebaseSession() {
	try {
		const profile = await db.userProfiles.get(1);
		if (!profile?.onboardingCompleted) return;
		await syncFirebaseUserProfile();
		await registerFcmToken();

		setDebtSyncNotifier((event) => {
			const amount = event.amount
				? `₱${Math.round(event.amount).toLocaleString("en-PH")}`
				: "";
			const who = event.who || "Someone";
			const debtTitle = event.noteTitle || "linked debt";
			let when = event.when || "";
			if (when) {
				const d = new Date(when + "T00:00:00");
				if (!Number.isNaN(d.getTime())) {
					when = d.toLocaleDateString("en-US", {
						month: "short",
						day: "numeric",
						year: "numeric",
					});
				}
			}

			if (event.kind === "payment" && event.amount) {
				const title = "Debt Note payment";
				const body = when
					? `${who} recorded ${amount} on ${when} for ${debtTitle}.`
					: `${who} recorded ${amount} for ${debtTitle}.`;
				void addAppNotification({ title, body, type: "debt_payment" });
				showDebtNotification(title, body);
			} else if (event.kind === "payment_pending" && event.amount) {
				const title = "Payment needs approval";
				const body = when
					? `${who} submitted ${amount} on ${when} for ${debtTitle}.`
					: `${who} submitted ${amount} for ${debtTitle}.`;
				void addAppNotification({ title, body, type: "debt_payment_pending" });
				showDebtNotification(title, body);
			} else if (event.kind === "payment_approved" && event.amount) {
				const title = "Payment approved";
				const body = when
					? `Your ${amount} payment on ${when} for ${debtTitle} was approved.`
					: `Your ${amount} payment for ${debtTitle} was approved.`;
				void addAppNotification({ title, body, type: "debt_payment_approved" });
				showDebtNotification(title, body);
			} else if (event.kind === "payment_rejected" && event.amount) {
				const title = "Payment rejected";
				const body = when
					? `Your ${amount} payment on ${when} for ${debtTitle} was rejected.`
					: `Your ${amount} payment for ${debtTitle} was rejected.`;
				void addAppNotification({ title, body, type: "debt_payment_rejected" });
				showDebtNotification(title, body);
			} else if (event.kind === "removed") {
				const title = "Debt Note removed";
				const body = "A linked debt entry was removed.";
				void addAppNotification({
					title,
					body,
					type: "debt_removed",
				});
				showDebtNotification(title, body);
			}
		});

		listenForegroundMessages(async (title, body, data) => {
			await applyDebtPushData(data);
			// Live sync notifier already records debt inbox items while the app is running.
			if (
				data.type === "debt_payment" ||
				data.type === "debt_payment_pending" ||
				data.type === "debt_payment_approved" ||
				data.type === "debt_payment_rejected" ||
				data.type === "debt_removed"
			) {
				return;
			}
			if (document.visibilityState === "visible") return;
			if (title || body) {
				void addAppNotification({
					title: title || "PocketFlow",
					body: body || "",
					type: data.type || "general",
					linkId: data.linkId,
				});
				showDebtNotification(title || "PocketFlow", body);
			}
		});

		await refreshGlobalDebtSync();

		document.addEventListener("visibilitychange", () => {
			if (document.visibilityState === "visible") {
				void refreshGlobalDebtSync();
			}
		});

		navigator.serviceWorker?.addEventListener("message", (event) => {
			if (event.data?.type !== "debt-push-click") return;
			void applyDebtPushData(event.data.data || {});
			void refreshGlobalDebtSync();
		});
	} catch (err) {
		console.warn("Firebase init skipped/failed:", err);
	}
}

void initFirebaseSession();
