import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
import { registerSW } from 'virtual:pwa-register'
import App from './App.vue'
import DashboardPage from './pages/dashboard/DashboardPage.vue'
import MonitoringPage from './pages/tracker/MonitoringPage.vue'
import ReportsPage from './pages/reports/ReportsPage.vue'
import MePage from './pages/me/MePage.vue'
import AccountPage from './pages/me/AccountPage.vue'
import ItemsPage from './pages/me/ItemsPage.vue'
import SavingsPage from './pages/me/SavingsPage.vue'
import AnalyticsPage from './pages/me/AnalyticsPage.vue'
import DebtNotePage from './pages/me/DebtNotePage.vue'
import ChatPage from './pages/chat/ChatPage.vue'
import OnboardingPage from './pages/auth/OnboardingPage.vue'
import LockScreen from './pages/auth/LockScreen.vue'
import './styles/main.css'
import { initTheme } from './composables/useTheme'
import { db, sessionUnlocked, restoreSessionUnlocked } from './db/budgetDb'

initTheme()

const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/', redirect: '/dashboard' },
    { path: '/dashboard', component: DashboardPage },
    { path: '/tracker', component: MonitoringPage },
    { path: '/reports', component: ReportsPage },
    { path: '/me', component: MePage },
    { path: '/me/account', component: AccountPage },
    { path: '/me/items', component: ItemsPage },
    { path: '/me/savings', component: SavingsPage },
    { path: '/me/analytics', component: AnalyticsPage },
    { path: '/me/debt-note', component: DebtNotePage },
    { path: '/chat', component: ChatPage },
    { path: '/onboarding', component: OnboardingPage },
    { path: '/lock', component: LockScreen },
  ],
})

router.beforeEach(async (to) => {
  const profile = await db.userProfiles.get(1)

  if (!profile?.onboardingCompleted) {
    if (to.path !== '/onboarding') return '/onboarding'
    return true
  }

  if (profile.lockEnabled && !sessionUnlocked) {
    restoreSessionUnlocked()
  }

  if (profile.lockEnabled && !sessionUnlocked) {
    if (to.path !== '/lock') return '/lock'
    return true
  }

  if (to.path === '/onboarding' || to.path === '/lock') return '/dashboard'

  return true
})

// Register the service worker generated by vite-plugin-pwa.
// autoUpdate: silently checks for updates and activates new SW when available.
const updateSW = registerSW({
  onNeedRefresh() {
    // New content is available; user can reload to get the latest version
    console.log('New content available. Reload to update.')
  },
  onOfflineReady() {
    // App shell is cached and ready to work offline
    console.log('App ready to work offline.')
  },
})

createApp(App).use(router).mount('#app')

// Expose update function globally if needed for manual refresh prompts
window.__pwaUpdateSW = updateSW
